name: fastapi

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Configure kubectl
      run: |
        aws eks --region ap-south-1 update-kubeconfig --name fastapi
        kubectl config current-context

    - name: fastapi
      run: kubectl apply -f path/to/your/deployment.yaml
